library(shiny)
library(networkD3)
library(shinydashboard)
library(DT)

sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("About", tabName = "about", icon = icon("dashboard")),

    menuItem("Start", icon = icon("th"), tabName = "start", 
      fileInput('file1',tags$h5(tags$b("Choose Patient Fold Change Data")), 
                accept=c('text/csv', 'text/comma-separated-values,text/plain', '.csv'))
    ), 
    
    menuItem("Drug Ranking", tabName = "table", icon = icon("dashboard")),

    menuItem("Network Visualization", icon = icon("th"), tabName = "network",
    	menuItem("Pnet", icon = icon("th"), tabName = "network1"),
    	menuItem("MoAnet", icon = icon("th"), tabName = "network2"),
    	menuItem("Merged Network", icon = icon("th"), tabName = "network3")
    )
))

body <- dashboardBody(
  tabItems(
    tabItem(tabName = "about",
      h2("Instructions of using MD-Miner:"),
      h3("1. Go to \"Start\" and click \"Browse\" to upload your fold change data."),
      h4("The average gene expression of duplicates of PC-3 and RWPE-1 cell lines are used to calculate the fold 
        change of gene expression."),
      h4("The uploaded file needs to be two columns: the first column being strings of gene names, 
        and the second column being values of their corresponding fold changes."),
      h4("For example:"),
      h5("\"GeneX\" 1.000000"),
      h5("\"CRTC1\" 0.829331"),
      h5("\"F2RL3\" 1.026998"),
      downloadLink('downloadData0', "Click here to download Demo.txt and upload it for a fun demo!"),
      h3("2. After the computation is complete, go to \"Drug Ranking\" to see the drug scores."),
      h4("If you want to download the data for drug ranking, click the download button on the upper left
        of the panel."),
      h3("3. Click on a drug entry in the table and see the networks in \"Network Visualization\". Pnet's 
      overlapped portion with the MoAnet will appear in orange nodes."),
      h4("You must have the drug remain clicked in the table to show the MoAnet and the merged network!"),
      h3("4. If you want to see the network generated by another drug, just go back to \"Drug Ranking\" 
        and clock on another drug entry."),
      h4("If you want to download the data for the network, click the download button at the upper left 
        of each panel. This .csv file also comprises of two columns: the first column are the source nodes 
        and the second column are the destination nodes.")
    ),

    tabItem(tabName = "table",
      fluidRow(
        box(title=downloadButton('downloadData', tags$b("Click to download Drug Scores")), value = tags$p(style = "font-size: 10px;", tags$b()),  solidHeader= TRUE,collapsible = TRUE, DT::dataTableOutput("table"), width =12)
        )
    ),

    tabItem(tabName = "network1",
      fluidRow(
        box(width = 12, title=downloadButton('downloadData1', tags$b("Click to download Patient-Specific Disease Signaling Network (Pnet)")), value = tags$p(style = "font-size: 10px;"), solidHeader= TRUE, collapsible = TRUE, forceNetworkOutput("patientNetwork", width = 1075))
        )
    ),

    tabItem(tabName = "network2",
      fluidRow(
        box(width = 12, title=downloadButton('downloadData2', tags$b("Click to download Mechanism of Action Signaling Network (MoAnet)")), value = tags$p(style = "font-size: 10px;"), solidHeader= TRUE, collapsible = TRUE,  forceNetworkOutput("drugNetwork", width = 1075))
        )
    ),

    # Hide the download button
    tabItem(tabName = "network3",
      fluidRow(
        box(width = 12, value = tags$p(style = "font-size: 10px;"), solidHeader= TRUE, collapsible = TRUE, forceNetworkOutput("mergeNetwork", width = 1075))
        )
    )

  )
)

shinyUI(fluidPage(theme = "bootstrap.css", 
    tags$style(type="text/css",
      "label {font-size: 12px;}",
      #"label {font-weight: bold;}",
      ".recalculating {opacity: 1.0;}"
    ),
    
    dashboardPage(skin = "yellow",
      dashboardHeader(title = tags$b("MD-Miner")),
	    sidebar,
	    body
    )

))